import "../styles/globals.css";
import "antd/dist/antd.css";
import "react-quill/dist/quill.snow.css";
import type { AppProps } from "next/app";
import Navbar from "../components/Navbar";
import Header from "../components/Header";
import AuthenticatedRoute from "../contexts/authenticatedRoute";
import { AuthProvider } from "../contexts/auth";
import Head from "next/head";

function MyApp({ Component, pageProps }: AppProps) {
    return (
        <>
            <Head>
                <title>JUWAN ADMIN</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/juwanfood-logo-short.png" />
            </Head>
            <AuthProvider>
                {/* <AuthenticatedRoute pathAfterFailure={"/login"}> */}
                <Navbar />
                <div style={{ marginLeft: "70px" }}>
                    <Header />
                    <div
                        style={{
                            padding: "20px",
                            width: "100%",
                            maxWidth: "1690px",
                            margin: "auto",
                        }}
                    >
                        <Component {...pageProps} />
                    </div>
                </div>
                {/* </AuthenticatedRoute> */}
            </AuthProvider>
        </>
    );
}

export default MyApp;
